package com.airdrive.backup.telegram

import android.content.Context
import android.util.Log
import com.airdrive.backup.BuildConfig
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import org.drinkless.tdlib.Client
import org.drinkless.tdlib.TdApi
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

enum class AuthState {
    UNKNOWN, WAIT_PHONE_NUMBER, WAIT_CODE, WAIT_PASSWORD, READY, LOGGED_OUT, CLOSED
}

class TdLibException(val code: Int, message: String) : Exception(message)

/**
 * Thin coroutine-friendly wrapper around org.drinkless.tdlib.Client (the JNI binding
 * generated by TDLib's own build, vendored in by CI — see build.gradle.kts). One instance
 * per process; the app keeps a single logged-in Telegram session for all uploads.
 */
class TdClient private constructor(private val appContext: Context) {

    private val tag = "AirDrive.TdClient"
    private var client: Client? = null

    private val _authState = MutableStateFlow(AuthState.UNKNOWN)
    val authState: StateFlow<AuthState> = _authState

    private val _lastAuthError = MutableStateFlow<String?>(null)
    val lastAuthError: StateFlow<String?> = _lastAuthError

    fun start() {
        if (client != null) return
        client = Client.create({ update -> handleUpdate(update) }, null, null)
    }

    private fun handleUpdate(update: TdApi.Object) {
        when (update) {
            is TdApi.UpdateAuthorizationState -> onAuthorizationState(update.authorizationState)
            else -> Unit
        }
    }

    private fun onAuthorizationState(state: TdApi.AuthorizationState) {
        when (state) {
            is TdApi.AuthorizationStateWaitTdlibParameters -> {
                val params = TdApi.SetTdlibParameters().apply {
                    useTestDc = false
                    databaseDirectory = appContext.filesDir.absolutePath + "/tdlib"
                    filesDirectory = appContext.filesDir.absolutePath + "/tdlib-files"
                    useFileDatabase = true
                    useChatInfoDatabase = true
                    useMessageDatabase = true
                    useSecretChats = false
                    apiId = BuildConfig.TELEGRAM_API_ID
                    apiHash = BuildConfig.TELEGRAM_API_HASH
                    systemLanguageCode = "en"
                    deviceModel = android.os.Build.MODEL ?: "Android"
                    systemVersion = android.os.Build.VERSION.RELEASE ?: "unknown"
                    applicationVersion = BuildConfig.VERSION_NAME
                }
                client?.send(params) { }
            }
            is TdApi.AuthorizationStateWaitPhoneNumber -> _authState.value = AuthState.WAIT_PHONE_NUMBER
            is TdApi.AuthorizationStateWaitCode -> _authState.value = AuthState.WAIT_CODE
            is TdApi.AuthorizationStateWaitPassword -> _authState.value = AuthState.WAIT_PASSWORD
            is TdApi.AuthorizationStateReady -> _authState.value = AuthState.READY
            is TdApi.AuthorizationStateLoggingOut -> _authState.value = AuthState.LOGGED_OUT
            is TdApi.AuthorizationStateClosed -> _authState.value = AuthState.CLOSED
            else -> Unit
        }
    }

    suspend fun submitPhoneNumber(phoneNumber: String) {
        send(TdApi.SetAuthenticationPhoneNumber(phoneNumber, null))
    }

    suspend fun submitCode(code: String) {
        send(TdApi.CheckAuthenticationCode(code))
    }

    suspend fun submitPassword(password: String) {
        send(TdApi.CheckAuthenticationPassword(password))
    }

    suspend fun logOut() {
        send(TdApi.LogOut())
    }

    /**
     * Uploads a local file (already staged from SAF into app cache by the caller) to
     * [chatId] with [caption], retrying automatically on FloodWait (error 429) by
     * honoring the server-supplied retry-after delay. Returns the sent message id.
     */
    suspend fun uploadFile(localPath: String, chatId: Long, caption: String): Long {
        var attempt = 0
        while (true) {
            try {
                val message = sendMessageWithDocument(localPath, chatId, caption)
                return message.id
            } catch (e: TdLibException) {
                if (e.code == 429) {
                    val retryAfter = Regex("\\d+").find(e.message ?: "")?.value?.toLongOrNull() ?: 5L
                    Log.w(tag, "FloodWait: retrying after ${retryAfter}s")
                    delay(retryAfter * 1000)
                    attempt++
                    if (attempt > 10) throw e
                } else {
                    throw e
                }
            }
        }
    }

    private suspend fun sendMessageWithDocument(localPath: String, chatId: Long, caption: String): TdApi.Message {
        val content = TdApi.InputMessageDocument(
            TdApi.InputFileLocal(localPath),
            TdApi.FormattedText(caption, emptyArray())
        )
        val sendRequest = TdApi.SendMessage().apply {
            this.chatId = chatId
            inputMessageContent = content
        }
        return send(sendRequest) as TdApi.Message
    }

    private suspend fun send(function: TdApi.Function<*>): TdApi.Object =
        suspendCancellableCoroutine { cont ->
            client?.send(function) { result ->
                if (result is TdApi.Error) {
                    cont.resumeWithException(TdLibException(result.code, result.message))
                } else {
                    cont.resume(result)
                }
            } ?: cont.resumeWithException(IllegalStateException("TDLib client not started"))
        }

    companion object {
        @Volatile private var instance: TdClient? = null

        fun get(context: Context): TdClient =
            instance ?: synchronized(this) {
                instance ?: TdClient(context.applicationContext).also {
                    it.start()
                    instance = it
                }
            }
    }
}
