package com.airdrive.backup.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.CloudDownload
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.PhoneAndroid
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import com.airdrive.backup.data.backup.ManifestSync
import com.airdrive.backup.data.db.BackupCategory
import com.airdrive.backup.data.repo.BackupRepository
import com.airdrive.backup.data.repo.MigrationState
import com.airdrive.backup.data.repo.RestoreState
import com.airdrive.backup.util.Format
import com.airdrive.backup.work.WorkScheduler
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

private val MBlue = Color(0xFF2F6FEA); private val MBlueLight = Color(0xFFDCEBFF); private val MPurple = Color(0xFF7C3AED); private val MPurpleLight = Color(0xFFF0DFFF); private val MGreen = Color(0xFF20A463); private val MGreenLight = Color(0xFFDDF6EC); private val MRed = Color(0xFFE84A5F); private val MRedLight = Color(0xFFFFE1E6); private val MOrange = Color(0xFFF59E0B); private val MOrangeLight = Color(0xFFFFEBD0); private val MCyan = Color(0xFF18B8C8); private val MBg = Color(0xFFF7F9FD); private val MText = Color(0xFF17213B); private val MSub = Color(0xFF6E7788)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MigrationScreen(nav: NavHostController) {
    val context = LocalContext.current; val repository = remember { BackupRepository.get(context) }; val scope = rememberCoroutineScope(); val totals by remember { repository.restorableTotalsFlow() }.collectAsState(initial = emptyList()); val restoredCount by remember { repository.restoredCountFlow() }.collectAsState(initial = 0); val migration by repository.migration.collectAsState(); val currentFile by repository.restoreState.collectAsState()
    var selected by remember { mutableStateOf(emptySet<BackupCategory>()) }; var skipRestored by remember { mutableStateOf(true) }; var scanning by remember { mutableStateOf(false) }; var scanMessage by remember { mutableStateOf<String?>(null) }; var confirmStartOver by remember { mutableStateOf(false) }; var primed by remember { mutableStateOf(false) }
    LaunchedEffect(totals) { if (!primed && totals.isNotEmpty()) { selected = totals.map { it.category }.toSet(); primed = true } }
    val byCategory = remember(totals) { totals.associateBy { it.category } }; val ordered = remember(byCategory) { BackupCategory.values().filter { byCategory.containsKey(it) } }; val selectedBytes = remember(selected, byCategory) { selected.sumOf { byCategory[it]?.bytes ?: 0L } }; var plannedFiles by remember { mutableStateOf(selected.sumOf { byCategory[it]?.count ?: 0 }) }
    LaunchedEffect(selected, skipRestored, restoredCount) { plannedFiles = if (selected.isEmpty()) 0 else repository.migrationQueueSize(selected, skipRestored) }

    Scaffold(containerColor = MBg, topBar = { TopAppBar(title = { Column { Text("Restore from old device", fontWeight = FontWeight.Bold, color = MText); Text("Bring your previous backup to this phone", style = MaterialTheme.typography.bodySmall, color = MSub) } }, navigationIcon = { IconButton(onClick = { nav.popBackStack() }) { Icon(Icons.Default.ArrowBack, "Back") } }, colors = TopAppBarDefaults.topAppBarColors(containerColor = MBg)) }) { padding ->
        Column(Modifier.fillMaxSize().padding(padding).verticalScroll(rememberScrollState()).padding(horizontal = 16.dp)) {
            Spacer(Modifier.height(10.dp))
            Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(22.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(1.dp)) { Column(Modifier.padding(18.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Surface(modifier = Modifier.size(52.dp), shape = RoundedCornerShape(17.dp), color = MBlueLight) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.PhoneAndroid, null, tint = MBlue, modifier = Modifier.size(30.dp)) } }; Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)) { Text("Your old phone is safe", fontWeight = FontWeight.Bold, color = MText, style = MaterialTheme.typography.titleMedium); Text("The backup index lives in your Telegram account.", style = MaterialTheme.typography.bodySmall, color = MSub) } }; Spacer(Modifier.height(14.dp)); Text("Sign in with the same Telegram account and AirDrive can rebuild the library without a cable or computer.", style = MaterialTheme.typography.bodyMedium, color = Color(0xFF4F5D78)) } }
            Spacer(Modifier.height(12.dp))
            ScanCard(hasIndex = totals.isNotEmpty(), scanning = scanning, message = scanMessage) { scanning = true; scanMessage = null; scope.launch { val result = runCatching { repository.restoreManifestForced() }; scanning = false; scanMessage = result.fold({ migrationScanText(it) }, { "Could not read the backup index: ${it.message}" }); if (result.isSuccess) primed = false } }
            Spacer(Modifier.height(16.dp))
            if (!migration.idle) { MigrationProgressCard(migration, currentFile, { WorkScheduler.cancelMigration(context); repository.markMigrationCancelled() }) { repository.clearMigrationState() }; Spacer(Modifier.height(14.dp)) }
            if (ordered.isNotEmpty()) {
                Row(verticalAlignment = Alignment.Bottom) { Column(Modifier.weight(1f)) { Text("Choose what to restore", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold, color = MText); Text("Select categories. Every file in the selected categories is included.", style = MaterialTheme.typography.bodySmall, color = MSub) }; Text("${selected.size}/${ordered.size}", color = MBlue, fontWeight = FontWeight.Bold) }
                Spacer(Modifier.height(10.dp))
                ordered.forEach { category -> val row = byCategory.getValue(category); CategoryCard(category, row.count, row.bytes, category in selected, !migration.running) { selected = if (category in selected) selected - category else selected + category }; Spacer(Modifier.height(8.dp)) }
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedButton(onClick = { selected = ordered.toSet() }, enabled = !migration.running && selected.size < ordered.size, modifier = Modifier.weight(1f), shape = RoundedCornerShape(14.dp)) { Text("Select all") }; OutlinedButton(onClick = { selected = emptySet() }, enabled = !migration.running && selected.isNotEmpty(), modifier = Modifier.weight(1f), shape = RoundedCornerShape(14.dp)) { Text("Clear") } }
                Spacer(Modifier.height(14.dp))
                Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(1.dp)) { Column(Modifier.padding(16.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Column(Modifier.weight(1f)) { Text("Resume safely", fontWeight = FontWeight.Bold, color = MText); Text("Skip files already restored", color = MText); Text("Turn this off only if you deliberately want another copy.", style = MaterialTheme.typography.bodySmall, color = MSub) }; Switch(checked = skipRestored, onCheckedChange = { skipRestored = it }, enabled = !migration.running) }; HorizontalDivider(Modifier.padding(vertical = 12.dp)); Text(if (selected.isEmpty()) "Nothing selected" else "${Format.count(plannedFiles)} files • ${migrationFormatBytes(selectedBytes)}", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = MText); Text(if (skipRestored) "Only files not restored on this phone will be downloaded." else "All selected files will be downloaded again.", style = MaterialTheme.typography.bodySmall, color = MSub) } }
                Spacer(Modifier.height(12.dp))
                Button(onClick = { repository.markMigrationQueued(); WorkScheduler.startMigration(context, selected, skipRestored) }, enabled = selected.isNotEmpty() && !migration.running, modifier = Modifier.fillMaxWidth().height(56.dp), shape = RoundedCornerShape(18.dp), colors = ButtonDefaults.buttonColors(containerColor = MBlue)) { Icon(Icons.Default.CloudDownload, null); Spacer(Modifier.width(8.dp)); Text(if (migration.running) "Restoring…" else "Start restore", fontWeight = FontWeight.Bold) }
                Spacer(Modifier.height(10.dp)); Text("Files arrive in Downloads/AirDrive/<Category>. Existing names are never overwritten, and WorkManager keeps the migration resumable if the app closes.", style = MaterialTheme.typography.bodySmall, color = MSub)
                if (restoredCount > 0) { Spacer(Modifier.height(14.dp)); Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = MGreenLight)) { Row(Modifier.padding(14.dp), verticalAlignment = Alignment.CenterVertically) { Icon(Icons.Default.CloudDownload, null, tint = MGreen); Spacer(Modifier.width(9.dp)); Text("${Format.count(restoredCount)} files have already been restored on this phone.", style = MaterialTheme.typography.bodySmall, color = MGreen, fontWeight = FontWeight.SemiBold) } }; TextButton(onClick = { confirmStartOver = true }, enabled = !migration.running) { Text("Start over") } }
            } else EmptyMigrationCard()
            Spacer(Modifier.height(28.dp))
        }
    }
    if (confirmStartOver) AlertDialog(onDismissRequest = { confirmStartOver = false }, title = { Text("Start over?") }, text = { Text("AirDrive will forget which files it has already restored. Nothing already downloaded will be deleted.") }, confirmButton = { TextButton(onClick = { confirmStartOver = false; scope.launch { repository.clearRestoreMarks(null) } }) { Text("Start over") } }, dismissButton = { TextButton(onClick = { confirmStartOver = false }) { Text("Cancel") } })
}

@Composable private fun ScanCard(hasIndex: Boolean, scanning: Boolean, message: String?, onScan: () -> Unit) { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = if (hasIndex) MBlueLight else Color.White), elevation = CardDefaults.cardElevation(0.dp)) { Row(Modifier.padding(16.dp), verticalAlignment = Alignment.CenterVertically) { Surface(modifier = Modifier.size(46.dp), shape = RoundedCornerShape(14.dp), color = Color.White.copy(alpha = .82f)) { Box(contentAlignment = Alignment.Center) { Icon(imageVector = if (hasIndex) Icons.Default.Refresh else Icons.Default.CloudDownload, contentDescription = null, tint = MBlue) } }; Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)) { Text(if (hasIndex) "Backup index found" else "Find your old backup", fontWeight = FontWeight.Bold, color = MText); Text(if (hasIndex) "Scan again if the old phone has backed up since the last scan." else "Read the file list stored in your Telegram account.", style = MaterialTheme.typography.bodySmall, color = MSub); message?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = MText) } }; if (scanning) CircularProgressIndicator(Modifier.size(22.dp), strokeWidth = 2.dp) else TextButton(onClick = onScan) { Text(if (hasIndex) "Scan again" else "Scan Telegram", color = MBlue) } } } }

@Composable private fun CategoryCard(category: BackupCategory, files: Int, bytes: Long, checked: Boolean, enabled: Boolean, onToggle: () -> Unit) { val (tint, bg, icon) = when (category) { BackupCategory.PHOTOS -> Triple(MGreen, MGreenLight, Icons.Default.Image); BackupCategory.VIDEOS -> Triple(MRed, MRedLight, Icons.Default.PlayArrow); BackupCategory.PDFS -> Triple(MOrange, MOrangeLight, Icons.Default.Description); BackupCategory.WORD_EXCEL -> Triple(MPurple, MPurpleLight, Icons.Default.Description); BackupCategory.AUDIO -> Triple(MCyan, Color(0xFFDDF7FA), Icons.Default.PlayArrow); BackupCategory.CALL_RECORDINGS -> Triple(MBlue, MBlueLight, Icons.Default.PhoneAndroid); BackupCategory.OTHER_FILES -> Triple(MCyan, Color(0xFFDDF7FA), Icons.Default.Description) }; Card(onClick = onToggle, enabled = enabled, modifier = Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(1.dp)) { Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) { Checkbox(checked, { onToggle() }, enabled = enabled); Surface(modifier = Modifier.size(46.dp), shape = RoundedCornerShape(14.dp), color = bg) { Box(contentAlignment = Alignment.Center) { Icon(imageVector = icon, contentDescription = null, tint = tint, modifier = Modifier.size(25.dp)) } }; Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)) { Text(categoryLabel(category), fontWeight = FontWeight.Bold, color = MText); Text("${Format.count(files)} files • ${migrationFormatBytes(bytes)}", style = MaterialTheme.typography.bodySmall, color = MSub) }; Surface(shape = RoundedCornerShape(9.dp), color = bg) { Text(if (checked) "Selected" else "Select", Modifier.padding(horizontal = 9.dp, vertical = 5.dp), style = MaterialTheme.typography.labelSmall, color = tint, fontWeight = FontWeight.SemiBold) } } } }

@Composable private fun MigrationProgressCard(state: MigrationState, fileState: RestoreState?, onCancel: () -> Unit, onDismiss: () -> Unit) { val container = when { state.error != null -> MRedLight; state.finished -> MGreenLight; else -> MBlueLight }; Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(20.dp), colors = CardDefaults.cardColors(containerColor = container), elevation = CardDefaults.cardElevation(0.dp)) { Column(Modifier.padding(16.dp)) { Row(verticalAlignment = Alignment.CenterVertically) { Surface(modifier = Modifier.size(44.dp), shape = RoundedCornerShape(13.dp), color = Color.White.copy(alpha = .8f)) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.CloudDownload, null, tint = if (state.error == null) MBlue else MRed) } }; Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(when { state.error != null -> "Restore stopped"; state.cancelled -> "Restore cancelled"; state.finished -> "Restore complete"; state.queued -> "Restore queued"; else -> "Restoring your library" }, fontWeight = FontWeight.Bold, color = MText); Text(if (state.filesTotal > 0) "${Format.count(state.filesDone)} of ${Format.count(state.filesTotal)} files" else "Preparing…", style = MaterialTheme.typography.bodySmall, color = MSub) } }; Spacer(Modifier.height(10.dp)); if (state.filesTotal > 0) LinearProgressIndicator(progress = { state.fraction }, modifier = Modifier.fillMaxWidth()); state.currentFile?.let { Text(it, Modifier.padding(top = 8.dp), maxLines = 1, overflow = TextOverflow.Ellipsis, style = MaterialTheme.typography.bodySmall, color = MText) }; if (fileState?.running == true) LinearProgressIndicator(progress = { fileState.fraction }, modifier = Modifier.fillMaxWidth().padding(top = 7.dp)); state.filesFailed.takeIf { it > 0 }?.let { Text("${Format.count(it)} files failed and can be retried.", Modifier.padding(top = 7.dp), style = MaterialTheme.typography.bodySmall, color = MRed) }; state.error?.let { Text(it, Modifier.padding(top = 7.dp), style = MaterialTheme.typography.bodySmall, color = MRed) }; Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) { if (state.running) TextButton(onClick = onCancel) { Text("Cancel") } else TextButton(onClick = onDismiss) { Text("Dismiss") } } } } }

@Composable private fun EmptyMigrationCard() { Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White)) { Column(Modifier.padding(20.dp), horizontalAlignment = Alignment.CenterHorizontally) { Icon(Icons.Default.CloudDownload, null, Modifier.size(44.dp), tint = MBlue); Spacer(Modifier.height(8.dp)); Text("No backup index yet", fontWeight = FontWeight.Bold, color = MText); Text("Tap Scan Telegram above to find the old phone's backup list.", style = MaterialTheme.typography.bodySmall, color = MSub) } } }
private fun migrationScanText(result: ManifestSync.RestoreResult): String = when (result) { is ManifestSync.RestoreResult.Restored -> { val date = SimpleDateFormat("d MMM yyyy, HH:mm", Locale.getDefault()).format(Date(result.manifestDateMillis)); "Found ${Format.count(result.fileCount)} backed-up files, indexed $date." }; ManifestSync.RestoreResult.NoManifestFound -> "No backup list found in this Telegram account."; ManifestSync.RestoreResult.NotSignedIn -> "Not signed in to Telegram yet."; ManifestSync.RestoreResult.NothingToDo -> "Already up to date."; is ManifestSync.RestoreResult.Failed -> "Could not read the backup list: ${result.reason}" }
private fun migrationFormatBytes(bytes: Long): String = when { bytes < 1024L -> "$bytes B"; bytes < 1024L * 1024L -> "%.1f KB".format(Locale.getDefault(), bytes / 1024.0); bytes < 1024L * 1024L * 1024L -> "%.1f MB".format(Locale.getDefault(), bytes / (1024.0 * 1024.0)); else -> "%.1f GB".format(Locale.getDefault(), bytes / (1024.0 * 1024.0 * 1024.0)) }