package com.airdrive.backup.ui.screens

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material.icons.filled.ArrowForward
import androidx.compose.material.icons.filled.CloudDownload
import androidx.compose.material.icons.filled.PhoneAndroid
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.SelectAll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.navigation.NavHostController
import com.airdrive.backup.data.db.BackupCategory
import com.airdrive.backup.data.db.FileRecord
import com.airdrive.backup.data.repo.BackupRepository
import com.airdrive.backup.util.MediaThumbnails
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.*

private val RBlue = Color(0xFF2F6FEA); private val RBlueLight = Color(0xFFDCEBFF); private val RPurple = Color(0xFF7C3AED); private val RPurpleLight = Color(0xFFF0DFFF); private val RGreen = Color(0xFF20A463); private val RGreenLight = Color(0xFFDDF6EC); private val RRed = Color(0xFFE84A5F); private val RRedLight = Color(0xFFFFE1E6); private val ROrange = Color(0xFFF59E0B); private val ROrangeLight = Color(0xFFFFEBD0); private val RCyan = Color(0xFF18B8C8); private val RBg = Color(0xFFF7F9FD); private val RText = Color(0xFF17213B); private val RSub = Color(0xFF6E7788)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RestoreScreen(nav: NavHostController) {
    val context = LocalContext.current; val repository = remember { BackupRepository.get(context) }; val scope = rememberCoroutineScope(); var query by remember { mutableStateOf("") }; var categoryFilter by remember { mutableStateOf<BackupCategory?>(null) }; var selected by remember { mutableStateOf(emptySet<Long>()) }; var bulkRunning by remember { mutableStateOf(false) }; var bulkDone by remember { mutableStateOf(0) }; var bulkFailed by remember { mutableStateOf(0) }; var bulkTotal by remember { mutableStateOf(0) }
    val records by remember(query, categoryFilter) { repository.restorableFlow(query.trim(), categoryFilter?.name ?: "", 5000) }.collectAsState(initial = emptyList()); val restore by repository.restoreState.collectAsState(); LaunchedEffect(records) { selected = selected.intersect(records.map { it.id }.toSet()) }; val allSelected = records.isNotEmpty() && selected.size == records.size; DisposableEffect(Unit) { onDispose { MediaThumbnails.trim() } }
    Scaffold(containerColor = RBg, topBar = { TopAppBar(title = { Column { Text("Restore", fontWeight = FontWeight.Bold, color = RText); Text("Get your files back, anytime", style = MaterialTheme.typography.bodySmall, color = RSub) } }, navigationIcon = { IconButton(onClick = { if (selected.isEmpty()) nav.popBackStack() else selected = emptySet() }) { Icon(Icons.Default.ArrowBack, "Back") } }, actions = { if (records.isNotEmpty()) TextButton(onClick = { selected = if (allSelected) emptySet() else records.map { it.id }.toSet() }) { Icon(Icons.Default.SelectAll, null, modifier = Modifier.size(19.dp), tint = RBlue); Spacer(Modifier.width(5.dp)); Text(if (allSelected) "Clear" else "Select all", color = RBlue) } }, colors = TopAppBarDefaults.topAppBarColors(containerColor = RBg)) }) { padding ->
        Column(Modifier.fillMaxSize().padding(padding)) {
            Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).padding(horizontal = 16.dp), horizontalArrangement = Arrangement.spacedBy(12.dp)) { PathCard("Restore from\nOld Device", "Full backup • resumable", Icons.Default.PhoneAndroid, RBlue, RBlueLight) { nav.navigate(Routes.MIGRATE) }; PathCard("Restore from\nTelegram", "Browse cloud copies", Icons.Default.CloudDownload, RPurple, RPurpleLight) { } }
            Spacer(Modifier.height(14.dp)); OutlinedTextField(value = query, onValueChange = { query = it }, leadingIcon = { Icon(Icons.Default.Search, null, tint = Color(0xFF596579)) }, placeholder = { Text("Search uploaded files…") }, singleLine = true, shape = RoundedCornerShape(18.dp), colors = OutlinedTextFieldDefaults.colors(unfocusedContainerColor = Color.White, focusedContainerColor = Color.White, unfocusedBorderColor = Color(0xFFD9DEEA), focusedBorderColor = RBlue), modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp).height(62.dp)); Spacer(Modifier.height(10.dp))
            Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).padding(horizontal = 16.dp), horizontalArrangement = Arrangement.spacedBy(8.dp)) { Chip("All", categoryFilter == null, RBlue, RBlueLight) { categoryFilter = null }; Chip("Photos", categoryFilter == BackupCategory.PHOTOS, RGreen, RGreenLight) { categoryFilter = if (categoryFilter == BackupCategory.PHOTOS) null else BackupCategory.PHOTOS }; Chip("Videos", categoryFilter == BackupCategory.VIDEOS, RRed, RRedLight) { categoryFilter = if (categoryFilter == BackupCategory.VIDEOS) null else BackupCategory.VIDEOS }; Chip("PDFs", categoryFilter == BackupCategory.PDFS, ROrange, ROrangeLight) { categoryFilter = if (categoryFilter == BackupCategory.PDFS) null else BackupCategory.PDFS }; Chip("Documents", categoryFilter == BackupCategory.WORD_EXCEL, RPurple, RPurpleLight) { categoryFilter = if (categoryFilter == BackupCategory.WORD_EXCEL) null else BackupCategory.WORD_EXCEL }; Chip("Audio", categoryFilter == BackupCategory.AUDIO, RCyan, Color(0xFFDDF7FA)) { categoryFilter = if (categoryFilter == BackupCategory.AUDIO) null else BackupCategory.AUDIO } }
            Spacer(Modifier.height(7.dp)); Row(Modifier.fillMaxWidth().padding(horizontal = 18.dp), verticalAlignment = Alignment.CenterVertically) { Text("${records.size} available", style = MaterialTheme.typography.labelLarge, color = RSub, modifier = Modifier.weight(1f)); if (selected.isNotEmpty()) Text("${selected.size} selected", style = MaterialTheme.typography.labelLarge, color = RBlue, fontWeight = FontWeight.Bold) }
            restore?.let { state -> Card(Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 6.dp), shape = RoundedCornerShape(16.dp), colors = CardDefaults.cardColors(containerColor = if (state.error == null) RBlueLight else RRedLight)) { Column(Modifier.padding(12.dp)) { Text(if (state.error != null) "Restore failed" else if (state.finishedPath != null) "Restore complete" else "Restoring ${state.fileName}…", fontWeight = FontWeight.Bold, color = RText); state.error?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = RRed) }; if (state.running) { Spacer(Modifier.height(6.dp)); LinearProgressIndicator(progress = { state.fraction }, modifier = Modifier.fillMaxWidth()) }; state.finishedPath?.let { Text("Saved to $it", style = MaterialTheme.typography.bodySmall, color = RGreen) } } } }
            if (records.isEmpty()) Box(Modifier.fillMaxSize(), contentAlignment = Alignment.Center) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Icon(Icons.Default.CloudDownload, null, Modifier.size(48.dp), tint = RBlue.copy(alpha = .6f)); Spacer(Modifier.height(9.dp)); Text(if (query.isBlank()) "No uploaded files to restore" else "No files match your search", color = RSub) } } else LazyColumn(Modifier.weight(1f).padding(horizontal = 16.dp), contentPadding = PaddingValues(top = 6.dp, bottom = if (selected.isEmpty()) 20.dp else 92.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { items(records, key = { it.id }) { record -> RestoreRecordCard(record, record.id in selected, restore?.running == true || bulkRunning, { selected = if (record.id in selected) selected - record.id else selected + record.id }) { scope.launch { runCatching { repository.restoreFile(record) } } } } }
            if (selected.isNotEmpty()) Button(onClick = { val targets = records.filter { it.id in selected }; bulkRunning = true; bulkDone = 0; bulkFailed = 0; bulkTotal = targets.size; scope.launch { for (record in targets) { runCatching { repository.restoreFile(record) }.onFailure { bulkFailed++ }; bulkDone++ }; bulkRunning = false; selected = emptySet() } }, enabled = !bulkRunning && restore?.running != true, modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 10.dp).height(54.dp), shape = RoundedCornerShape(18.dp), colors = ButtonDefaults.buttonColors(containerColor = RBlue)) { Icon(Icons.Default.CloudDownload, null); Spacer(Modifier.width(8.dp)); Text(if (bulkRunning) "Restoring $bulkDone / $bulkTotal" else "Restore ${selected.size} selected", fontWeight = FontWeight.Bold) }
        }
    }
}

@Composable private fun PathCard(title: String, subtitle: String, icon: androidx.compose.ui.graphics.vector.ImageVector, tint: Color, bg: Color, onClick: () -> Unit) { Card(onClick = onClick, modifier = Modifier.width(190.dp).height(146.dp), shape = RoundedCornerShape(22.dp), colors = CardDefaults.cardColors(containerColor = bg), elevation = CardDefaults.cardElevation(0.dp)) { Box(Modifier.fillMaxSize().padding(16.dp)) { Surface(modifier = Modifier.size(48.dp), shape = RoundedCornerShape(16.dp), color = Color.White.copy(alpha = .86f)) { Box(contentAlignment = Alignment.Center) { Icon(imageVector = icon, contentDescription = null, tint = tint, modifier = Modifier.size(28.dp)) } }; Column(Modifier.padding(top = 58.dp).padding(end = 30.dp)) { Text(title, fontWeight = FontWeight.Bold, color = RText, style = MaterialTheme.typography.titleMedium); Text(subtitle, style = MaterialTheme.typography.bodySmall, color = Color(0xFF52627D)) }; Surface(modifier = Modifier.align(Alignment.BottomEnd).size(36.dp), shape = RoundedCornerShape(50), color = Color.White.copy(alpha = .9f)) { Box(contentAlignment = Alignment.Center) { Icon(Icons.Default.ArrowForward, null, tint = tint) } } } } }
@Composable private fun Chip(label: String, selected: Boolean, tint: Color, bg: Color, onClick: () -> Unit) { FilterChip(selected = selected, onClick = onClick, label = { Text(label, fontWeight = if (selected) FontWeight.SemiBold else FontWeight.Normal) }, shape = RoundedCornerShape(14.dp), colors = FilterChipDefaults.filterChipColors(selectedContainerColor = bg, selectedLabelColor = tint, containerColor = Color.White, labelColor = RSub), border = FilterChipDefaults.filterChipBorder(enabled = true, selected = selected, borderColor = Color(0xFFD9DEEA), selectedBorderColor = tint)) }
@Composable private fun RestoreRecordCard(record: FileRecord, checked: Boolean, busy: Boolean, onToggle: () -> Unit, onRestore: () -> Unit) { val context = LocalContext.current; val fmt = remember { SimpleDateFormat("MMM d, HH:mm", Locale.getDefault()) }; var bitmap by remember(record.uri) { mutableStateOf(MediaThumbnails.peek(record)) }; LaunchedEffect(record.uri) { if (bitmap == null) bitmap = MediaThumbnails.load(context, record) }; val accent = when (record.category) { BackupCategory.PHOTOS -> RGreen; BackupCategory.VIDEOS -> RRed; BackupCategory.PDFS -> ROrange; BackupCategory.WORD_EXCEL -> RPurple; BackupCategory.AUDIO -> RCyan; BackupCategory.CALL_RECORDINGS -> RBlue; BackupCategory.OTHER_FILES -> RCyan }; Card(Modifier.fillMaxWidth(), shape = RoundedCornerShape(18.dp), colors = CardDefaults.cardColors(containerColor = Color.White), elevation = CardDefaults.cardElevation(1.dp)) { Row(Modifier.fillMaxWidth().padding(8.dp), verticalAlignment = Alignment.CenterVertically) { Checkbox(checked, { onToggle() }, enabled = !busy); Box(Modifier.size(64.dp).clip(RoundedCornerShape(13.dp)).background(accent.copy(alpha = .12f)), contentAlignment = Alignment.Center) { bitmap?.let { Image(bitmap = it.asImageBitmap(), contentDescription = record.displayName, contentScale = ContentScale.Crop, modifier = Modifier.fillMaxSize()) } ?: Text(record.displayName.substringAfterLast('.', "FILE").uppercase(Locale.getDefault()).take(5), color = accent, style = MaterialTheme.typography.labelSmall) }; Spacer(Modifier.width(10.dp)); Column(Modifier.weight(1f)) { Text(record.displayName, fontWeight = FontWeight.SemiBold, color = RText, maxLines = 1, overflow = TextOverflow.Ellipsis); Text("${com.airdrive.backup.ui.screens.formatBytes(record.sizeBytes)} • ${record.uploadedAtMillis?.let { fmt.format(Date(it)) } ?: "uploaded"}", style = MaterialTheme.typography.bodySmall, color = RSub); Surface(shape = RoundedCornerShape(8.dp), color = accent.copy(alpha = .12f)) { Text(categoryLabel(record.category), Modifier.padding(horizontal = 7.dp, vertical = 3.dp), style = MaterialTheme.typography.labelSmall, color = accent, fontWeight = FontWeight.SemiBold) } }; Spacer(Modifier.width(6.dp)); Button(onClick = onRestore, enabled = !busy, shape = RoundedCornerShape(14.dp), colors = ButtonDefaults.buttonColors(containerColor = RBlue), contentPadding = PaddingValues(horizontal = 12.dp, vertical = 8.dp)) { Icon(Icons.Default.CloudDownload, null, modifier = Modifier.size(18.dp)); Spacer(Modifier.width(4.dp)); Text("Restore") } } } }
